### ISSUE TITLE
通过 AUR 安装无法打开

### ISSUE THREAD

**Issue by Discreater** [Neutree/COMTool#120]
无论是 python-comtool 还是 python-comtool-git 都无法打开。
日志如下
```shell
❯ comtool
2024-01-17 12:14:34 - [INFO] -  Config path: /home/alkaid/.config/comtool/config.json
2024-01-17 12:14:34 - [INFO] -  Log path: /home/alkaid/.config/comtool/run.log
2024-01-17 12:14:34 - [INFO] -  loading config from /home/alkaid/.config/comtool/config.json
2024-01-17 12:14:34 - [INFO] -  loading config complete
-- set locale to en
== translate locales: ['en', 'zh_CN', 'zh_TW', 'ja'] ==
-- generate en mo file from po files
2024-01-17 12:14:34 - [INFO] - compiling catalog locales/en/LC_MESSAGES/messages.po to locales/en/LC_MESSAGES/messages.mo
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/COMTool/Main.py", line 4, in <module>
    from main2 import main
ModuleNotFoundError: No module named 'main2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/comtool", line 5, in <module>
    from COMTool.Main import main
  File "/usr/lib/python3.11/site-packages/COMTool/Main.py", line 7, in <module>
    from COMTool.main2 import main
  File "/usr/lib/python3.11/site-packages/COMTool/main2.py", line 24, in <module>
    i18n.set_locale(programConfig["locale"])
  File "/usr/lib/python3.11/site-packages/COMTool/i18n.py", line 27, in set_locale
    main("finish")
  File "/usr/lib/python3.11/site-packages/COMTool/i18n.py", line 134, in main
    compile("locales", locale)
  File "/usr/lib/python3.11/site-packages/COMTool/i18n.py", line 92, in compile
    cmdinst.run()
  File "/usr/lib/python3.11/site-packages/babel/messages/frontend.py", line 198, in run
    for errors in self._run_domain(domain).values():
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/babel/messages/frontend.py", line 271, in _run_domain
    with open(mo_file, 'wb') as outfile:
         ^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'locales/en/LC_MESSAGES/messages.mo'

```

**Comment by Discreater** [comment]
sudo 后可以打开，但是还是希望能解决一下这个问题。

**Comment by Neutree** [comment]
AUR 是网友维护的一个版本，我没有精力去维护，所以出现问题时建议直接从 release页面下在二进制文件，或者直接 `pip install comtool `安装
