### ISSUE TITLE
Ubuntu20.04无法移动窗口

### ISSUE THREAD

**Issue by YanZhaoNo1** [Neutree/COMTool#130]
我是使用pip3 install comtool 指令下载的，在移动窗口的时候会报一个错误
Traceback (most recent call last):
  File "/home/yan/.local/lib/python3.8/site-packages/COMTool/widgets.py", line 265, in eventFilter
    self.moveOrResize(obj.windowHandle(), event.pos(), obj.width(), obj.height())
  File "/home/yan/.local/lib/python3.8/site-packages/COMTool/widgets.py", line 243, in moveOrResize
    window.startSystemMove()
AttributeError: 'QWindow' object has no attribute 'startSystemMove'
不知道i怎么去解决这个问题了

**Comment by Neutree** [comment]
你安装的 qt版本比较旧 不支持 startSystemMove 这个函数，你可以直接下载 release里面打包好的二进制版本，或者升级一下pyqt5
