### ISSUE TITLE
python3.12 兼容问题，imp 在 py3.12 已被弃用

### ISSUE THREAD

**Issue by wirano** [Neutree/COMTool#138]
在 python 3.12 中，imp 已被[移除](https://docs.python.org/3/whatsnew/3.12.html#imp)

```
Traceback (most recent call last):
File "/usr/lib/python3.12/site-packages/COMTool/Main.py", line 4, in <module>
from main2 import main
ModuleNotFoundError: No module named 'main2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
ModuleNotFoundError: No module named 'helpAbout'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/bin/comtool", line 5, in <module>
from COMTool.Main import main
File "/usr/lib/python3.12/site-packages/COMTool/Main.py", line 7, in <module>
from COMTool.main2 import main
File "/usr/lib/python3.12/site-packages/COMTool/main2.py", line 43, in <module>
from COMTool.pluginItems import PluginItem
File "/usr/lib/python3.12/site-packages/COMTool/pluginItems.py", line 1, in <module>
import imp
ModuleNotFoundError: No module named 'imp'
import imp
ModuleNotFoundError: No module named 'imp'
```

**Comment by Neutree** [comment]
ok 了，直接删了，这个应该是误引入的，实际没用到：https://github.com/Neutree/COMTool/commit/012b33722504d2e5d61ec4bfda056dd2c29c19b9
