### ISSUE TITLE
Raspberry运行出错

### ISSUE THREAD

**Issue by xieakun** [Neutree/COMTool#18]
%Run Main.py
libEGL warning: DRI2: failed to authenticate
qt5ct: using qt5ct plugin
Traceback (most recent call last):
  File "/home/pi/Desktop/Program/COMTool-master/COMTool/Main.py", line 799, in <module>
    main()
  File "/home/pi/Desktop/Program/COMTool-master/COMTool/Main.py", line 783, in main
    mainWindow = MainWindow(app)
  File "/home/pi/Desktop/Program/COMTool-master/COMTool/Main.py", line 54, in __init__
    pathDirList.pop()
IndexError: pop from empty list
>>> inotify_add_watch("/home/pi/.config/qt5ct") failed: "No such file or directory"

**Comment by xieakun** [comment]
Solved the problem，thanks all the same。
Could you tell me how to solve the relative address problem of python on the Raspberry Pi 3?

**Comment by Neutree** [comment]
what relative address problem? maybe you can change relative path to absolute path?
