### ISSUE TITLE
pycharm调试失败

### ISSUE THREAD

**Issue by fbcgithub** [Neutree/COMTool#59]

**Comment by fbcgithub** [comment]
error: Traceback (most recent call last):
  File "D:\py-project\wlan\COMTool-master\COMTool-master\COMTool\main2.py", line 697, in main
    mainWindow = MainWindow(app, eventFilter, programConfig)
  File "D:\py-project\wlan\COMTool-master\COMTool-master\COMTool\main2.py", line 81, in __init__
    self.initWindow()
  File "D:\py-project\wlan\COMTool-master\COMTool-master\COMTool\main2.py", line 320, in initWindow
    self.titleBar = TitleBar(self, icon=iconPath, title=title, brothers=[], widgets=[[self.skinButton, self.aboutButton], []])
  File "D:\py-project\wlan\COMTool-master\COMTool-master\COMTool\widgets.py", line 73, in __init__
    utils_ui.setButtonIcon(self.top, btnIcons[3][0])
  File "D:\py-project\wlan\COMTool-master\COMTool-master\COMTool\utils_ui.py", line 42, in setButtonIcon
    button.setIcon(qta.icon(icon, color=iconColor))
  File "D:\Anaconda\envs\python38\lib\site-packages\qtawesome\__init__.py", line 173, in icon
    return _instance().icon(*names, **kwargs)
  File "D:\Anaconda\envs\python38\lib\site-packages\qtawesome\iconic_font.py", line 304, in icon
    parsed_options.append(self._parse_options(specific_options,
  File "D:\Anaconda\envs\python38\lib\site-packages\qtawesome\iconic_font.py", line 354, in _parse_options
    prefix, chars = self._get_prefix_chars(names)
  File "D:\Anaconda\envs\python38\lib\site-packages\qtawesome\iconic_font.py", line 388, in _get_prefix_chars
    raise Exception(error)
Exception: Invalid font prefix "ph"

**Comment by Neutree** [comment]
更新一下图标库 `pip install -U qtawesome`

**Comment by fbcgithub** [comment]
成功了，万分感谢！
