### ISSUE TITLE
ModuleNotFoundError: No module named 'matplotlib'

### ISSUE THREAD

**Issue by marklove5102** [Neutree/COMTool#71]
`````
[make@archlinux COMTool]$ python COMTool/Main.py
2022-08-11 18:17:07 - [INFO] -  Config path: /home/make/.config/comtool/config.json
2022-08-11 18:17:07 - [INFO] -  Log path: /home/make/.config/comtool/run.log
2022-08-11 18:17:07 - [INFO] -  loading config from /home/make/.config/comtool/config.json
2022-08-11 18:17:07 - [INFO] -  loading config complete
-- set locale to en
Traceback (most recent call last):
  File "/home/make/COMTool/COMTool/plugins/gragh.py", line 14, in <module>
    from plugins.gragh_widgets import graghWidgets
  File "/home/make/COMTool/COMTool/plugins/gragh_widgets.py", line 12, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
`````
虽然手动安装解决了。但是加入requirements.txt列表不好吗？

**Comment by Neutree** [comment]
这是 昨天的 PR（#70） 引入的 bug 哈哈哈， 引入 matplot 太大了，会将其移除 #72  用Pillow代替了
