### ISSUE TITLE
提示缺少main2、helpAbout、Combobox等module

### ISSUE THREAD

**Issue by YangZhouDL** [Neutree/COMTool#93]
你好，我系统是Ubuntu 18.04，Python版本3.7.5，QT版本5.12.2
能够顺利pips install comtool，但是在终端运行时如下错误
```bash
redwall@redwall-G3-3500:~$ comtool
2023-03-07 19:10:10 - [INFO] -  Config path: /home/redwall/.config/comtool/config.json
2023-03-07 19:10:10 - [INFO] -  Log path: /home/redwall/.config/comtool/run.log
2023-03-07 19:10:10 - [INFO] -  loading config from /home/redwall/.config/comtool/config.json
2023-03-07 19:10:10 - [INFO] -  loading config complete
-- set locale to en
Traceback (most recent call last):
  File "/home/redwall/.local/lib/python3.7/site-packages/COMTool/Main.py", line 4, in <module>
    from main2 import main
ModuleNotFoundError: No module named 'main2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/redwall/.local/lib/python3.7/site-packages/COMTool/main2.py", line 27, in <module>
    import helpAbout,autoUpdate
ModuleNotFoundError: No module named 'helpAbout'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/redwall/.local/lib/python3.7/site-packages/COMTool/plugins/graph.py", line 9, in <module>
    from Combobox import ComboBox
ModuleNotFoundError: No module named 'Combobox'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/redwall/.local/bin/comtool", line 5, in <module>
    from COMTool.Main import main
  File "/home/redwall/.local/lib/python3.7/site-packages/COMTool/Main.py", line 7, in <module>
    from COMTool.main2 import main
  File "/home/redwall/.local/lib/python3.7/site-packages/COMTool/main2.py", line 42, in <module>
    from COMTool.plugins import builtinPlugins
  File "/home/redwall/.local/lib/python3.7/site-packages/COMTool/plugins/__init__.py", line 4, in <module>
    from . import graph
  File "/home/redwall/.local/lib/python3.7/site-packages/COMTool/plugins/graph.py", line 21, in <module>
    from COMTool.plugins.graph_widgets import graphWidgets
  File "/home/redwall/.local/lib/python3.7/site-packages/COMTool/plugins/graph_widgets.py", line 22, in <module>
    from .graph_widget_metasenselite import Graph_MetaSenseLite
  File "/home/redwall/.local/lib/python3.7/site-packages/COMTool/plugins/graph_widget_metasenselite.py", line 9, in <module>
    from PIL import Image
  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 60, in <module>
    from . import _imaging as core
ImportError: cannot import name '_imaging' from 'PIL' (/usr/lib/python3/dist-packages/PIL/__init__.py)
```
提示缺少main2、helpAbout、Combobox等module，这些module用pip无法安装，应该是包内部的，不知道怎么解决呢

**Comment by Neutree** [comment]
`ImportError: cannot import name '_imaging' from 'PIL' (/usr/lib/python3/dist-packages/PIL/__init__.py)` 这个才是错误原因， pillow 这个包估计有问题，你看一下 pillow 这个包的版本，`pip3 list`， 可以升级一下这个包`pip3 install pillow -U`试试

**Comment by YangZhouDL** [comment]
非常感谢！！！`pip3 list`查看后pillow为5版本，`pip3 install pillow -U`升级后为9版本，comtool可以正常打开
